#!/usr/bin/env python
# encoding=utf8

# my version of xxd
#
# python because ö doesn't have io yet and... well, you can't use ö to
# compile the ö interpreter

import sys
import textwrap

# python 2 sucks at unicode, even in a very simple script!!
if sys.version_info[0] <= 2:
    code = sys.stdin.read().decode('utf-8')
else:
    code = sys.stdin.read()

output = []
for char in code:
    output.append(hex(ord(char)))

print(textwrap.fill(', '.join(output)))
